.TH service 8 "August 2018" "Pygos Init"
.SH NAME
service \- configure or administrate system services
.SH SYNOPSIS
.B service
<command>
[options]
.SH DESCRIPTION
The service command can be used to configure, control and administrate services
supervised by the init daemon.
.SH COMMANDS
.TP
.BR help " " \fI[command]\fP
If no arguments are provided, displays a short help text and a list of all
available commands with a short description for each.

If a command name is specified, displays a more elaborate description and
usage information for the specified command.
.TP
.BR list " " \fI[target]\fP
Displays a list of currently enabled services. If an optional target is
specified, lists services only for this target, otherwise, list services
for all targets.
.TP
.BR enable " " \fI<service>\fP " " \fI[arguments]\fP
Enable (but do not start) a system service by creating a symlink in the
configuration directory, pointing to the service template file.

An optional argument can be supplied to parameterize the template.
.TP
.BR disable " " \fI<service>\fP " " \fI[arguments]\fP
Disable (but do not stop) a system service by removing the corresponding
symlink in the configuration directory.

If the service is parameterized, arguments have to be specified to disable
the desired service instance.
.TP
.BR dumpscript " " \fI<service>\fP " " \fI[arguments]\fP
Parse a service file from and produce a pseudo shell script containing the
exact commands executed when starting the service.
.TP
.BR status " " \fI[--detail|-d]\fP " " \fI[services...]\fP
Print a status report of all supervised services, i.e. if they are currently
running, have exited or waiting to be scheduled. A specific list of services
can be specified. Shell globbing patterns can be used.
.TP
.BR start " " \fIservices...\fP
Start one or more currently not running services. Shell globbing patterns can be used.
.TP
.BR stop " " \fIservices...\fP
Stop one or more currently running services. Shell globbing patterns can be used.
.SH AVAILABILITY
This program is part of the Pygos init system.
.SH COPYRIGHT
Copyright \(co 2018 David Oberhollenzer
.br
License: ISC <https://www.gnu.org/licenses/license-list.html#ISC>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR sync (2),
.BR reboot (2)
